# syntax=docker/dockerfile:1

# stage 1
FROM eclipse-temurin:24.0.2_12-jre AS jre-py

## Install python/pip
ENV PYTHONUNBUFFERED=1
# Install Python runtime and pip
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends python3 python3-venv python3-pip ca-certificates && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*
# Create isolated venv and install deps
ENV VIRTUAL_ENV=/opt/py
ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"
RUN python3 -m venv "${VIRTUAL_ENV}" && \
    pip install --no-cache-dir --upgrade pip setuptools wheel && \
    pip install --no-cache-dir pyvis==0.3.2 pandas==2.2.3

# Create a group and user
RUN groupadd --system --gid 1001 gedcomanalyzerapp && \
    useradd  --system --uid 1001 --no-create-home --gid 1001 --shell /usr/sbin/nologin gedcomanalyzeruser

# stage 2
FROM jre-py AS jre-py-app
COPY --chown=gedcomanalyzeruser:gedcomanalyzerapp target/*.jar app.jar
VOLUME /tmp
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app.jar"]
