runtime: java17
instance_class: F4_1G
entrypoint: java -jar -Dspring.profiles.active=prod gedcom-analyzer-0.0.1-SNAPSHOT.jar
env_variables:
  CLOUD_SQL_INSTANCE: ""
  CLOUD_SQL_USER: ""
  CLOUD_SQL_PASS: ""
