runtime: java17
instance_class: B4
basic_scaling:
  idle_timeout: 1800s
  max_instances: 1
entrypoint: java -jar -Dspring.profiles.active=prod gedcom-analyzer-0.8.1-SNAPSHOT.jar
env_variables:
  CLOUD_SQL_INSTANCE: ""
  CLOUD_SQL_USER: ""
  CLOUD_SQL_PASS: ""
