<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Genea Azul</title>
    <meta charset="UTF-8" />
    <meta name="description" content="Genea Azul. Estudio de genealog&iacute;a azule&ntilde;a." />
    <meta name="keywords" content="genealogia, historia familiar, arbol genealogico, ascendencia, descendencia, azul, ciudad de azul" />
    <meta name="author" content="Nico Ciri" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="robots" content="noindex" />
    <meta http-equiv="cache-control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="refresh" content="2; URL='https://geneaazul.com.ar'" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" integrity="sha384-XGjxtQfXaH2tnPFa9x+ruJTuLE3Aa6LhHSWRr1XeTyhezb4abCG4ccI5AkVDxqC+" crossorigin="anonymous" />
    <style>
      body {
          height: 100vh;
      }
    </style>
  </head>

  <body class="container">

    <div class="d-flex flex-column align-items-center justify-content-center" id="loading-container">
      <img class="img-fluid" src="img/genea-azul-logo.png?v1" alt="Genea Azul logo" />
    </div>

    <!-- Footer -->
    <div class="alert alert-light bg-light text-center small mt-4 mb-0" role="alert">
      <p>
        <b>Genea Azul</b> es una iniciativa comunitaria sin fines de lucro con el fin de investigar, documentar y preservar la historia geneal&oacute;gica del partido de Azul.
      </p>
      <p>
        Declarado de <b>Inter&eacute;s Comunitario, Hist&oacute;rico y Cultural</b> por el Concejo Deliberante de Azul.
      </p>
      <p>
        &iexcl;Solicit&aacute; acceso al &aacute;rbol y carg&aacute; info!
      </p>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js" integrity="sha384-NXgwF8Kv9SSAr+jemKKcbvQsz+teULH/a5UNJvZc6kP47hZgl62M1vGnw6gHQhb1" crossorigin="anonymous"></script>
  </body>

</html>
